Mapbox geocoding+directions on Rails
NikolayGGorbunov/delivery_rails pull request #1
Opened 2022-08-19 09:08 UTC by NikolayGGorbunov

2022-08-19 11:16 UTC, Sh1mensoka requested changes
Why don't we add coverage and bin directories in .gitignore to reduce PR's size?

2022-08-19 11:16 UTC, Sh1mensoka commented on config/application.rb
> +HOSTNAME = ENV['HOSTNAME']
nit: we don't need this

2022-08-19 11:16 UTC, Sh1mensoka commented on lib/delivery/deliveryboy.rb
> +require 'pry'
We don't need this as long as we work with Rails

2022-08-19 11:16 UTC, Sh1mensoka commented on lib/delivery/deliveryboy.rb
> +      cubic = length * width * height
Do we really need this variable if it's used only once?

2022-08-19 11:16 UTC, Sh1mensoka commented on spec/controllers/packages_controller_spec.rb
> +  end
We don't need to create 2 packages before every test suite

2022-08-19 11:16 UTC, Sh1mensoka commented on spec/controllers/packages_controller_spec.rb
> +  end
It should be moved to spec_helper

2022-08-19 11:16 UTC, Sh1mensoka commented on spec/controllers/packages_controller_spec.rb
> +        expect(pack_create).to redirect_to("/packages/#{Package.last.id}")
We should use route helpers in `redirect_to` cases, not hardcoded links

2022-08-19 11:16 UTC, Sh1mensoka commented on spec/controllers/packages_controller_spec.rb
> +  describe 'create' do
All instance method's descriptions should look like "#<method_name>"

2022-08-19 11:21 UTC, NikolayGGorbunov commented on app/views/packages/_package.html.erb
> +<h2><%= link_to "New package", root_path %></h2>
Got it, fixed

2022-08-19 11:21 UTC, NikolayGGorbunov commented on app/views/packages/create.html.erb
> +<p>Find me in app/views/packages/create.html.erb</p>
Deleted

2022-08-19 11:22 UTC, NikolayGGorbunov commented on app/views/packages/delete.html.erb
> +<p>Find me in app/views/packages/delete.html.erb</p>
Deleted. They was created automatically when I generate model

2022-08-19 11:23 UTC, NikolayGGorbunov commented on app/views/packages/index.html.erb
> +<h2><%= link_to "New package", root_path %></h2>
Changed

2022-08-19 11:29 UTC, NikolayGGorbunov commented on lib/delivery/deliveryboy.rb
> +require 'pry'
Changed. Removing NET/HTTP causes API-request to drop

2022-08-19 11:31 UTC, NikolayGGorbunov commented on lib/delivery/deliveryboy.rb
> +      cubic = length * width * height
It was used before I rewrite this part of method. Fixed

2022-08-19 12:14 UTC, NikolayGGorbunov commented on spec/controllers/packages_controller_spec.rb
> +  end
Fixed by adding additional context

2022-08-19 12:17 UTC, NikolayGGorbunov commented on spec/controllers/packages_controller_spec.rb
> +  end
Fixed

2022-08-19 12:21 UTC, NikolayGGorbunov commented on spec/controllers/packages_controller_spec.rb
> +        expect(pack_create).to redirect_to("/packages/#{Package.last.id}")
Fixed

2022-08-19 12:21 UTC, NikolayGGorbunov commented on spec/controllers/packages_controller_spec.rb
> +  describe 'create' do
Fixed

2022-08-19 13:24 UTC, Sh1mensoka commented on spec/support/factory_bot.rb
> +end
Why don't we move it to spec_helper.rb?

2022-08-19 13:28 UTC, NikolayGGorbunov commented on spec/support/factory_bot.rb
> +end
fixed

2022-08-19 13:34 UTC, Sh1mensoka approved these changes

2022-08-23 18:39 UTC, NadezhdaGlin commented on spec/controllers/packages_controller_spec.rb
> +
What's happen when we will not specify some field?

2022-08-24 07:47 UTC, NikolayGGorbunov commented on spec/controllers/packages_controller_spec.rb
> +
Program raise exception 'Param missing'
But I think it can't happen because Package model have a bunch of parameter validations and form also require all parameters.
So we can get 'param missing' only from console

2022-08-24 07:51 UTC, NadezhdaGlin approved these changes

2022-08-24 07:52 UTC, merged